udp_address: 0.0.0.0:33333
graphite_target: tcp://127.0.0.1:3002
monitoring_enabled: true
monitoring_path: servers.pirate_foe.software.pirate.{metric.name}
gzip: true
log_level: info
projects:
  foe_mobile:
    graphite_path: AVG.games.foe.client.{attr.market}.{attr.platform}.{attr.version}.{metric.name}
    attributes:
      market: ^(none|[a-z]{2})$
      platform: ^(ios|and(_(google|amazon|samsung))?)$
      version: ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))?$
    metrics:
      fps:
        min: 0
        max: 70
      memory_usage:
        min: 0
        max: 2147483648
      startup_time:
        min: 0
        max: 120